MONGODB_HOST: mongodb-{{ env }}.rajkumardaws.space # mongodb-dev.rajkumardaws.space
REDIS_HOST: redis-{{ env }}.rajkumardaws.space
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.rajkumardaws.space
CART_HOST: cart.backend-alb-{{ env }}.rajkumardaws.space
USER_HOST: user.backend-alb-{{ env }}.rajkumardaws.space
RABBITMQ_HOST: rabbitmq-{{ env }}.rajkumardaws.space
MYSQL_HOST: mysql-{{ env }}.rajkumardaws.space
SHIPPING_HOST: shipping.backend-alb-{{ env }}.rajkumardaws.space
PAYMENT_HOST: payment.backend-alb-{{ env }}.rajkumardaws.space